#pragma once

#define AUDIO_CTRL_NODE "/dev/bonovo_handle"
#define HANDLE_CTRL_DEV_MAJOR 230
#define HANDLE_CTRL_DEV_MINOR 0
#define IOCTL_HANDLE_GET_RADIO_STATUS _IO(HANDLE_CTRL_DEV_MAJOR, 3)
#define IOCTL_HANDLE_START_RADIO_SEARCH _IO(HANDLE_CTRL_DEV_MAJOR, 4)
#define IOCTL_HANDLE_STOP_RADIO_SEARCH _IO(HANDLE_CTRL_DEV_MAJOR, 5)
#define IOCTL_HANDLE_GET_RADIO_CURR_FREQ _IO(HANDLE_CTRL_DEV_MAJOR, 6)
#define IOCTL_HANDLE_GET_RADIO_FREQ _IO(HANDLE_CTRL_DEV_MAJOR, 7)
#define IOCTL_HANDLE_CODEC_SWITCH_SRC _IO(HANDLE_CTRL_DEV_MAJOR, 30)
#define IOCTL_HANDLE_CODEC_RECOVER_SRC _IO(HANDLE_CTRL_DEV_MAJOR, 31)

const char* RADIO_DEV_NODE = "/dev/ttyS3";

enum Commands {
  CMD_RADIO_STANDARD_MODEL = 0,
  CMD_RADIO_BAND_SELECT = 1,
  CMD_RADIO_RDS_ON_OFF = 2,
  CMD_RADIO_VOLUME = 3,
  CMD_RADIO_MUTE = 4,
  CMD_RADIO_FREQ = 5,
  CMD_RADIO_START_SEARCH = 6,
  CMD_RADIO_STOP_SEARCH = 7,
  CMD_RADIO_STEREO_STRENGTHEN = 8,
  CMD_RADIO_SHUTDOWN = 9,
  CMD_RADIO_MIN_FREQ = 10,
  CMD_RADIO_MAX_FREQ = 11,
  CMD_RADIO_STEP_LEN = 12,
  CMD_RADIO_REMOTE = 13
};

struct radio_freq {
  unsigned char freq[2];
  unsigned char is_valid;
};

const char* RDS_CTRL_NODE = "/dev/bonovo_rds";

#define RDS_DEV_MAJOR 237

#define RDS_IOCTL_START_DATA _IO(RDS_DEV_MAJOR, 0)  // request rds data
#define RDS_IOCTL_STOP_DATA _IO(RDS_DEV_MAJOR, 1)  // stop transfer rds data to android


